export const randomCar: string[] = [
  'Ford Focus',
  'Ford Mustang',
  'Ford Fusion',
  'Ford Fiesta',
  'Ford Transit',
  'Ford Explorer',
  'Ford Figo',
  'Ford Aspire',
  'Ford Ecosport',
  'Ford Freestyle',
  'Tesla Model S',
  'Tesla Model 3',
  'Tesla Model X',
  'Tesla Model Y',
  'Tesla Cybertruck',
  'BMW 3 Series',
  'BMW X5',
  'BMW i8',
  'Audi A4',
  'Audi Q7',
  'Audi e-tron',
  'Mercedes-Benz C-Class',
  'Mercedes-Benz GLE',
  'Mercedes-Benz EQS',
  'Toyota Corolla',
  'Toyota Camry',
  'Toyota RAV4',
  'Honda Civic',
  'Honda Accord',
  'Honda CR-V',
];
